# Assignment is below at the end

- https://scikit-learn.org/stable/modules/tree.html
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.plot_tree.html

In [7]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (20, 6)
plt.rcParams['font.size'] = 14
import pandas as pd

In [8]:
df = pd.read_csv('~/Desktop/adult.data', index_col=False)

In [9]:
golden = pd.read_csv('~/Desktop//adult.test', index_col=False)

In [10]:
golden.head()

age   workclass  fnlwgt      education  education-num       marital-status  \
0   25     Private  226802           11th              7        Never-married   
1   38     Private   89814        HS-grad              9   Married-civ-spouse   
2   28   Local-gov  336951     Assoc-acdm             12   Married-civ-spouse   
3   44     Private  160323   Some-college             10   Married-civ-spouse   
4   18           ?  103497   Some-college             10        Never-married   

           occupation relationship    race      sex  capital-gain  \
0   Machine-op-inspct    Own-child   Black     Male             0   
1     Farming-fishing      Husband   White     Male             0   
2     Protective-serv      Husband   White     Male             0   
3   Machine-op-inspct      Husband   Black     Male          7688   
4                   ?    Own-child   White   Female             0   

   capital-loss  hours-per-week  native-country   salary  
0             0              40   United-States   <=50K.  
1             0              50   United-States   <=50K.  
2             0              40   United-States    >50K.  
3             0              40   United-States    >50K.  
4             0              30   United-States   <=50K.

In [11]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [12]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [13]:
from sklearn import preprocessing

In [14]:
# Columns we want to transform
transform_columns = ['sex']

#Columns we can't use because non-numerical
non_num_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country']

## First let's try using `pandas.get_dummies()` to transform columns

In [15]:
dummies = pd.get_dummies(df[transform_columns])
dummies

sex_ Female  sex_ Male
0                0          1
1                0          1
2                0          1
3                0          1
4                1          0
...            ...        ...
32556            1          0
32557            0          1
32558            1          0
32559            0          1
32560            1          0

[32561 rows x 2 columns]

In [16]:
dummies.shape

(32561, 2)

## sklearn has a similar process for OneHot Encoding features

In [55]:
from sklearn import preprocessing
enc = preprocessing.OrdinalEncoder()

onehot = preprocessing.OneHotEncoder(handle_unknown="infrequent_if_exist", sparse_output=False)
onehot.fit(df[transform_columns])

TypeError: __init__() got an unexpected keyword argument 'sparse_output'

In [18]:
onehot.categories_

AttributeError: 'OneHotEncoder' object has no attribute 'categories_'

In [19]:
sex = onehot.transform(df[transform_columns])
sex

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [20]:
sex.shape

NameError: name 'sex' is not defined

## In addition to OneHot encoding there is Ordinal Encoding 

In [37]:
enc = preprocessing.OrdinalEncoder()
enc.fit(df[["salary"]])
salary = enc.transform(df[["salary"]])
salary

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [38]:
enc.categories_[0]

array([' <=50K', ' >50K'], dtype=object)

In [43]:
x = df.copy()

# transformed = pd.get_dummies(df[transform_columns])


#onehot = preprocessing.OneHotEncoder(handle_unknown="infrequent_if_exist", sparse=False).fit(df[transform_columns])

#transformed = onehot.transform(df[transform_columns])
#new_cols = list(onehot.categories_[0].flatten())
#df_trans = pd.DataFrame(transformed, columns=new_cols)


#x = pd.concat(
#   [
#        x.drop(non_num_columns, axis=1), 
#        df_trans
#    ], 
#    axis=1,)


#x["salary"] = enc.transform(df[["salary"]])

enc = preprocessing.OrdinalEncoder()

enc.fit(df[["salary"]])

x = df.copy()
x=pd.concat([x.drop(non_num_columns, axis=1),
             pd.get_dummies(df[transform_columns])], axis=1)
x["salary"] = enc.fit_transform(df[["salary"]])

In [44]:
x.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   salary  sex_ Female  sex_ Male  
0     0.0            0          1  
1     0.0            0          1  
2     0.0            0          1  
3     0.0            0          1  
4     0.0            1          0

In [46]:
xt = golden.copy()

#transformed = onehot.transform(xt[transform_columns])
#new_cols = list(onehot.categories_[0].flatten())
#df_trans = pd.DataFrame(transformed, columns=new_cols)

#x = pd.concat(
#    [
#        xt.drop(non_num_columns, axis=1), 
#        df_trans
#    ], 
#    axis=1,)

#xt["salary"] = enc.fit_transform(golden[["salary"]])

xt=pd.concat([xt.drop(non_num_columns, axis=1),
             pd.get_dummies(xt[transform_columns])], axis=1)
xt["salary"] = enc.fit_transform(xt[["salary"]])

In [47]:
xt.salary.value_counts()

0.0    12435
1.0     3846
Name: salary, dtype: int64

In [48]:
enc.categories_

[array([' <=50K.', ' >50K.'], dtype=object)]

In [49]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

#### Choose the model of your preference: DecisionTree or RandomForest

In [50]:
model = RandomForestClassifier(criterion='entropy')

In [51]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=None)

In [31]:
model.fit(x.drop(['fnlwgt','salary'], axis=1), x.salary)

ValueError: could not convert string to float: ' State-gov'

In [52]:
model.tree_.node_count

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

In [53]:
list(zip(x.drop(['fnlwgt','salary'], axis=1).columns, model.feature_importances_))

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [34]:
list(zip(x.drop(['fnlwgt','salary'], axis=1).columns, model.feature_importances_))

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

In [22]:
x.drop(['fnlwgt','salary'], axis=1).head()

age  education-num  capital-gain  capital-loss  hours-per-week  \
0   39             13          2174             0              40   
1   50             13             0             0              13   
2   38              9             0             0              40   
3   53              7             0             0              40   
4   28             13             0             0              40   

   sex_ Female  sex_ Male  
0            0          1  
1            0          1  
2            0          1  
3            0          1  
4            1          0

In [23]:
set(x.columns) - set(xt.columns)

set()

In [24]:
list(x.drop('salary', axis=1).columns)

['age',
 'fnlwgt',
 'education-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'sex_ Female',
 'sex_ Male']

In [55]:
predictions = model.predict(xt.drop(['fnlwgt','salary'], axis=1))
predictionsx = model.predict(x.drop(['fnlwgt','salary'], axis=1))

In [26]:
from sklearn.metrics import (
    accuracy_score, 
    classification_report, 
    confusion_matrix, auc, roc_curve
)

In [45]:
accuracy_score(xt.salary, predictions)

0.8213868926970088

In [57]:
accuracy_score(xt.salary, predictions)

0.82808181315644

In [46]:
confusion_matrix(xt.salary, predictions)

array([[11472,   963],
       [ 1945,  1901]])

In [47]:
print(classification_report(xt.salary, predictions))

              precision    recall  f1-score   support

         0.0       0.86      0.92      0.89     12435
         1.0       0.66      0.49      0.57      3846

    accuracy                           0.82     16281
   macro avg       0.76      0.71      0.73     16281
weighted avg       0.81      0.82      0.81     16281



In [56]:
print(classification_report(xt.salary, predictions))

              precision    recall  f1-score   support

         0.0       0.86      0.92      0.89     12435
         1.0       0.68      0.52      0.59      3846

    accuracy                           0.83     16281
   macro avg       0.77      0.72      0.74     16281
weighted avg       0.82      0.83      0.82     16281



In [48]:
accuracy_score(x.salary, predictionsx)

0.8955806025613464

In [49]:
confusion_matrix(x.salary, predictionsx)

array([[24097,   623],
       [ 2777,  5064]])

In [50]:
print(classification_report(x.salary, predictionsx))

              precision    recall  f1-score   support

         0.0       0.90      0.97      0.93     24720
         1.0       0.89      0.65      0.75      7841

    accuracy                           0.90     32561
   macro avg       0.89      0.81      0.84     32561
weighted avg       0.90      0.90      0.89     32561



In [58]:
print(classification_report(x.salary, predictionsx))

              precision    recall  f1-score   support

         0.0       0.91      0.96      0.93     24720
         1.0       0.85      0.68      0.76      7841

    accuracy                           0.90     32561
   macro avg       0.88      0.82      0.85     32561
weighted avg       0.89      0.90      0.89     32561



# For the following use the above `adult` dataset. 

# 1. Show the RandomForest outperforms the DecisionTree for a fixed `max_depth` by training using the train set and calculate `precision`, `recall`, `f1`, `confusion matrix` on golden-test set. Start with only numerical features/columns. (age, education-num, capital-gain, capital-loss, hours-per-week) 

In [153]:
import sklearn
sklearn.__version__

from sklearn import tree
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [155]:
num_columns = ['age', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
x_num = x[num_columns].copy()
xt_num = xt[num_columns].copy()
y_train = x['salary']
y_test = xt['salary']

KeyError: 'salary'

In [156]:
dtc_model = DecisionTreeClassifier(criterion='entropy', max_depth=10)
dtc_model.fit(x_num, y_train)
dtc_predictions = dtc_model.predict(xt_num)

In [157]:
print("Decision Tree Classifier (Numerical Features Only)")
print("Accuracy:", accuracy_score(y_test, dtc_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, dtc_predictions))
print("Classification Report:\n", classification_report(y_test, dtc_predictions))

Decision Tree Classifier (Numerical Features Only)
Accuracy: 0.8326884098028376
Confusion Matrix:
 [[11699   736]
 [ 1988  1858]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.85      0.94      0.90     12435
         1.0       0.72      0.48      0.58      3846

    accuracy                           0.83     16281
   macro avg       0.79      0.71      0.74     16281
weighted avg       0.82      0.83      0.82     16281



In [158]:
rfc_model = RandomForestClassifier(criterion='entropy', max_depth=10)
rfc_model.fit(x_num, y_train)
rfc_predictions = rfc_model.predict(xt_num)

In [159]:
print("Random Forest Classifier (Numerical Features Only)")
print("Accuracy:", accuracy_score(y_test, rfc_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, rfc_predictions))
print("Classification Report:\n", classification_report(y_test, rfc_predictions))

Random Forest Classifier (Numerical Features Only)
Accuracy: 0.8379706406240403
Confusion Matrix:
 [[11957   478]
 [ 2160  1686]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.85      0.96      0.90     12435
         1.0       0.78      0.44      0.56      3846

    accuracy                           0.84     16281
   macro avg       0.81      0.70      0.73     16281
weighted avg       0.83      0.84      0.82     16281



# 2. Use a RandomForest or DecisionTree and the `adult` dataset, systematically add new columns, one by one, that are non-numerical but converted using the feature-extraction techniques we learned. Using the golden-test set show [`precision`, `recall`, `f1`, `confusion matrix`] for each additional feature added.

In [181]:
transform_columns = ['sex', 'race']

non_num_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country']
x2 = df.copy()

x2 = pd.concat([x2.drop(non_num_columns, axis=1), 
               pd.get_dummies(df[transform_columns])], axis=1)

x2["salary"] = enc.fit_transform(df[["salary"]])

xt2 = golden.copy()

xt2 = pd.concat([xt2.drop(non_num_columns, axis=1), 
               pd.get_dummies(golden[transform_columns])], axis=1,)

xt2["salary"] = enc.fit_transform(golden[["salary"]])
x2.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   salary  sex_ Female  sex_ Male  race_ Amer-Indian-Eskimo  \
0     0.0            0          1                         0   
1     0.0            0          1                         0   
2     0.0            0          1                         0   
3     0.0            0          1                         0   
4     0.0            1          0                         0   

   race_ Asian-Pac-Islander  race_ Black  race_ Other  race_ White  
0                         0            0            0            1  
1                         0            0            0            1  
2                         0            0            0            1  
3                         0            1            0            0  
4                         0            1            0            0

In [197]:
x2.drop(['fnlwgt','salary'], axis=1).head()
model3 = RandomForestClassifier(criterion='entropy', max_depth=10)

model3.fit(x2.drop(['fnlwgt','salary'], axis=1), x2.salary)

predictions3 = model3.predict(xt2.drop(['fnlwgt','salary'], axis=1))
list(zip(x2.drop(['fnlwgt','salary'], axis=1).columns, model3.feature_importances_))


print(classification_report(xt2.salary, predictions3))

              precision    recall  f1-score   support

         0.0       0.87      0.96      0.91     12435
         1.0       0.79      0.53      0.64      3846

    accuracy                           0.86     16281
   macro avg       0.83      0.74      0.77     16281
weighted avg       0.85      0.86      0.85     16281



In [199]:
#Adding Marital Status
transform_columns = ['sex', 'race', 'marital-status']

non_num_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country']
xm2 = df.copy()

xm2 = pd.concat([xm2.drop(non_num_columns, axis=1), 
               pd.get_dummies(df[transform_columns])], axis=1)

xm2["salary"] = enc.fit_transform(df[["salary"]])

xmt2 = golden.copy()

xmt2 = pd.concat([xmt2.drop(non_num_columns, axis=1), 
               pd.get_dummies(golden[transform_columns])], axis=1,)

xmt2["salary"] = enc.fit_transform(golden[["salary"]])

model4 = RandomForestClassifier(criterion='entropy', max_depth=10)


model4.fit(xm2.drop(['fnlwgt','salary'], axis=1), xm2.salary)


predictions4 = model4.predict(xmt2.drop(['fnlwgt','salary'], axis=1))

list(zip(xm2.drop(['fnlwgt','salary'], axis=1).columns, model4.feature_importances_))

accuracy_score(xmt2.salary, predictions4)
confusion_matrix(xmt2.salary, predictions4)
print(classification_report(xmt2.salary, predictions4))

              precision    recall  f1-score   support

         0.0       0.87      0.96      0.91     12435
         1.0       0.80      0.53      0.64      3846

    accuracy                           0.86     16281
   macro avg       0.84      0.74      0.78     16281
weighted avg       0.85      0.86      0.85     16281



In [201]:
#Adding Education
transform_columns = ['sex', 'race', 'marital-status', 'education']

non_num_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country']
xe2 = df.copy()

xe2 = pd.concat([xe2.drop(non_num_columns, axis=1), 
               pd.get_dummies(df[transform_columns])], axis=1)

xe2["salary"] = enc.fit_transform(df[["salary"]])

xet2 = golden.copy()

xet2 = pd.concat([xet2.drop(non_num_columns, axis=1), 
               pd.get_dummies(golden[transform_columns])], axis=1,)

xet2["salary"] = enc.fit_transform(golden[["salary"]])

model5 = RandomForestClassifier(criterion='entropy', max_depth=10)

model5.fit(xe2.drop(['fnlwgt','salary'], axis=1), xe2.salary)

predictions5 = model5.predict(xet2.drop(['fnlwgt','salary'], axis=1))

list(zip(xe2.drop(['fnlwgt','salary'], axis=1).columns, model5.feature_importances_))

accuracy_score(xet2.salary, predictions5)
confusion_matrix(xet2.salary, predictions5)
print(classification_report(xt2.salary, predictions5))

              precision    recall  f1-score   support

         0.0       0.87      0.96      0.91     12435
         1.0       0.79      0.53      0.64      3846

    accuracy                           0.86     16281
   macro avg       0.83      0.74      0.77     16281
weighted avg       0.85      0.86      0.85     16281



In [202]:
#Adding Workclass

transform_columns = ['sex', 'race', 'marital-status', 'education', 'workclass']

non_num_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country']

xw2 = df.copy()

xw2 = pd.concat([xw2.drop(non_num_columns, axis=1), 
               pd.get_dummies(df[transform_columns])], axis=1)

xw2["salary"] = enc.fit_transform(df[["salary"]])

xwt2 = golden.copy()

xwt2 = pd.concat([xwt2.drop(non_num_columns, axis=1), 
               pd.get_dummies(golden[transform_columns])], axis=1,)

xwt2["salary"] = enc.fit_transform(golden[["salary"]])

model6 = RandomForestClassifier(criterion='entropy', max_depth=10)

model6.fit(xw2.drop(['fnlwgt','salary'], axis=1), xw2.salary)

predictions6 = model6.predict(xwt2.drop(['fnlwgt','salary'], axis=1))

list(zip(xw2.drop(['fnlwgt','salary'], axis=1).columns, model6.feature_importances_))

accuracy_score(xwt2.salary, predictions3)
confusion_matrix(xwt2.salary, predictions3)
print(classification_report(xwt2.salary, predictions3))


              precision    recall  f1-score   support

         0.0       0.87      0.96      0.91     12435
         1.0       0.80      0.53      0.64      3846

    accuracy                           0.86     16281
   macro avg       0.84      0.75      0.78     16281
weighted avg       0.85      0.86      0.85     16281

